setup.py: use open instead of file
When doing a pip3 install, the `file` from long_description is not defined.

Collecting https://github.com/enix223/modem/archive/refs/heads/multi-protocol.zip (from -r requirements.txt (line 5))
  Downloading https://github.com/enix223/modem/archive/refs/heads/multi-protocol.zip
     \ 184kB 2.4MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-2kc3v90y-build/setup.py", line 10, in <module>
        long_description = file('doc/source/about.rst').read(),
    NameError: name 'file' is not defined